// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadkhezgohlzpmqmhkbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZGtoZXpnb2hsenBtcW1oa2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDE4MjcsImV4cCI6MjA2NTQ3NzgyN30.KPdlmux_8P3v69-0QxUTkMCO5GST75ifuWXWlJk8Yr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);